### ISSUE TITLE
fix encapsulated packet

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/node-raknet#22]
http://wiki.vg/Pocket_Edition_Protocol_Documentation#Frame_Set_Packet

turns out raklib is ignoring some case that never happen in mcpe : "Sequenced frame index" here

**Comment by GiantQuartz** [comment]
I am having an issue too, I think it is related to this one as it emitted the error in `Client.readEncapsulatedPacket()`. Basically, I created a RakNet server and joined using my mcbe 1.14.30 client to see the output, it ended up crashing.

P.S.: Is this project still being maintained? I am trying to create a MCPE server software with JS and I am using this library to save myself a bunch of hours figuring out how to build a RakNet implementation from scratch.

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Read error for name : 254 is not in the mappings value
    at ProtoDef.readMapper (E:\Sauce\Sauce\node_modules\protodef\src\datatypes\utils.js:30:34)
    at ProtoDef.read (E:\Sauce\Sauce\node_modules\protodef\src\protodef.js:110:29)
    at E:\Sauce\Sauce\node_modules\protodef\src\datatypes\structures.js:45:32
    at tryCatch (E:\Sauce\Sauce\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (E:\Sauce\Sauce\node_modules\protodef\src\utils.js:54:10)
    at E:\Sauce\Sauce\node_modules\protodef\src\datatypes\structures.js:44:5
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (E:\Sauce\Sauce\node_modules\protodef\src\datatypes\structures.js:43:12)
    at ProtoDef.read (E:\Sauce\Sauce\node_modules\protodef\src\protodef.js:36:25)
    at ProtoDef.read (E:\Sauce\Sauce\node_modules\protodef\src\protodef.js:110:29)
Emitted 'error' event on Client instance at:
    at Client.readEncapsulatedPacket (E:\Sauce\Sauce\node_modules\raknet\src\client.js:132:12)
    at E:\Sauce\Sauce\node_modules\raknet\src\client.js:113:20
    at Array.forEach (<anonymous>)
    at Parser.<anonymous> (E:\Sauce\Sauce\node_modules\raknet\src\client.js:104:29)
    at Parser.emit (events.js:311:20)
    at addChunk (E:\Sauce\Sauce\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (E:\Sauce\Sauce\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Parser.Readable.push (E:\Sauce\Sauce\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Parser.Transform.push (E:\Sauce\Sauce\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Parser._transform (E:\Sauce\Sauce\node_modules\protodef\src\serializer.js:53:12) {
  field: 'name'
}

```

**Comment by mhsjlw** [comment]
This project is currently unmaintained, if you are interested in fixing this issue please make a PR

**Comment by TehcJS** [comment]
I'd be happy to help with this bug. I'll get around to this very soon.

**Comment by mhsjlw** [comment]
Late to this, but if you need any help feel free to ask here.
